#!/bin/bash
drwxr-xr-x 2 root root 97 Mar 11 14:17 . drwxr-xr-x 4 root root 60 Mar 11 13:02 .. -rwxr--r-- 1 root root 62 Mar 11 13:35 0-current_working_directory-rwxr--r-- 1 root root 61 Mar 11 13:54 1-listit -rwxr--r-- 1 root root 17 Mar 11 14:17 2-bring_me_home -rw-r--r-- 1 root root 60 Mar 11 13:17 README.md
